### PR TITLE
Deprecate support for Python 3.5 since it is no longer actively maintained

### PR DESCRIPTION
**Pull request by minhtuev**
Python 3.5 is no longer actively supported so we should remove it; this will also simplify our platform and infrastructure.

https://github.com/cisco/mindmeld/issues/221

### CODE REVIEW

**Comment by jjjacksn** [comment]
I get failures for black. Should we apply the format fixes from it?

```bash
16:28:54 (pr/228 $=) ~/code/cisco/mindmeld
! $ ./lintme
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/_version.py
would reformat /Users/jdot/code/cisco/mindmeld/examples/custom_action/example_server/swagger_server/test/test_default_controller.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/client.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/app_manager.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/request.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/_elasticsearch_helpers.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/gazetteer.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/embedder_models.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/converter/dialogflow.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/entity_resolver.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/helpers.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/cli.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/converter/rasa.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/core.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/taggers/embeddings.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/_config.py
would reformat /Users/jdot/code/cisco/mindmeld/setup.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/markup.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/taggers/taggers.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/text_models.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/path.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_auto_fill.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/nlp.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/components/dialogue.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/system_entity_recognizer.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/food_ordering/config.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/home_assistant/config.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_custom_action.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_dialogue.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/resource_loader.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_dialogue_async.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/conftest.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/model.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/kwik_e_mart/config.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_parser.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/taggers/lstm.py
would reformat /Users/jdot/code/cisco/mindmeld/mindmeld/models/query_features.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/models/test_text_models.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/models/test_tagging.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/components/test_nlp.py
would reformat /Users/jdot/code/cisco/mindmeld/tests/test_query_features.py
Oh no! 💥 💔 💥
41 files would be reformatted, 93 files would be left unchanged.
/Users/jdot/.pyenv/versions/3.7.8/envs/mm37/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
************* Module mindmeld.turn
mindmeld/turn.py:151:0: R0902: Too many instance attributes (12/11) (too-many-instance-attributes)
--- (truncated) ---
```

**Comment by minhtuev** [comment]
@jjjacksn : I thought I have already pinned all the dependencies? Let's apply the lint fixes and see what they are.

**Comment by minhtuev** [comment]
@jjjacksn : I have created this PR to apply the black changes:
https://github.com/cisco/mindmeld/pull/231

**Review by vijay120 — APPROVED** [review]

**Comment by vijay120** [comment]
@jjjacksn  Can we merge this PR?

**Review by serapio — APPROVED** [review]

**Pull request merged**
